### ISSUE TITLE
Repeat Timer Chain

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/Just-Practice#23]
**Value Proposition**
As a Musician I need to repeat the timer chain to be able to do the exercises several times in a row.

**Des
![repeat timer chain](https://user-images.githubusercontent.com/109812125/204548252-254087fd-13bd-47ed-b86f-f85f0674c98f.png)
cription**

**Acceptance Criteria**
- [x] The edit page shows a check box with which the repeat function can be activated.
- [x] If activated, the timer chain runs in continuous loop.

**Tasks**
- [x] Create an `input type"checkbox"`.
- [x] Create a `useState` and assign the value.
- [x] Write logic to repeat the timer chain.
